name: Flutter Build + s3

on:
  push:
    branches: ["production"]

jobs:
  deploy:
    name: Flutter build
    runs-on: ubuntu-latest

    steps:
      - name: Configure user credentials
        run: |
          git config --global credential.helper store
          echo https://${arquitetura-dev@nasajon.com.br}:${FVvmL94JWAgbtfR8}@github.com >> /root/.git-credentials
    
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: |
          echo "Iniciando build flutter"
          # flutter build web
          flutter build web --web-renderer html

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync build/web/ s3://arquitetura-api-docs
